const CROP_EMOJIS = {
  'Tomato':        '🍅',
  'Potato':        '🥔',
  'Onion':         '🧅',
  'Garlic':        '🧄',
  'Ginger':        '🫚',
  'Wheat':         '🌾',
  'Rice':          '🍚',
  'Maize':         '🌽',
  'Mustard':       '🌻',
  'Sugarcane':     '🎋',
  'Cotton':        '🌿',
  'Soybean':       '🫘',
  'Groundnut':     '🥜',
  'Chickpea':      '🫘',
  'Lentil':        '🫘',
  'Green Gram':    '🫘',
  'Black Gram':    '🫘',
  'Pigeon Pea':    '🫘',
  'Carrot':        '🥕',
  'Radish':        '🌱',
  'Spinach':       '🥬',
  'Fenugreek':     '🌿',
  'Coriander':     '🌿',
  'Chilli':        '🌶️',
  'Brinjal':       '🍆',
  'Okra':          '🫑',
  'Pumpkin':       '🎃',
  'Bottle Gourd':  '🥒',
  'Bitter Gourd':  '🥒',
  'Cucumber':      '🥒',
  'Cauliflower':   '🥦',
  'Cabbage':       '🥬',
  'Peas':          '🫛',
  'Ridge Gourd':   '🥒',
  'Drumstick':     '🌿',
  'Sweet Potato':  '🍠',
  'Taro':          '🥔',
  'Turnip':        '🌱',
  'Beetroot':      '🫐',
  'French Beans':  '🫛',
  'Cowpea':        '🫛',
  'Cluster Beans': '🫛',
  'Banana':        '🍌',
  'Mango':         '🥭',
  'Guava':         '🍈',
  'Papaya':        '🍈',
  'Watermelon':    '🍉',
  'Grapes':        '🍇',
  'Pomegranate':   '🍎',
  'Lemon':         '🍋',
  'Turmeric':      '🟡',
  'Cumin':         '🌿',
  'Sesame':        '🌾',
  'Sorghum':       '🌾',
  'Pearl Millet':  '🌾',
  'Finger Millet': '🌾',
  'Barley':        '🌾',
  'Sunflower':     '🌻',
  'Castor':        '🌿',
  'Jute':          '🌿',
};

export default CROP_EMOJIS;
